### ISSUE TITLE
[BE] TODO LIST

### ISSUE THREAD

**Issue by jihoon1** [codestates/beb-05-KNS#19]
# 

- Bare Minimum (필수) - 프로젝트에서 **반드시 달성**해야 하는 항목입니다.
    - 1) **NodeJS 서버 생성**
        - [x]  Express를 사용하여 기본 서버를 생성하기
        - [x]  router 설정하기
        - [x]  dotenv를 이용하여 중요정보를 환경변수로 저장하기
    - 2) **DB 연결**
        - [x]  서버와 연동
    - 3) **스마트 컨트랙트 연동**
        - [ ] #33
    - 4) **필요한 API 작성**
        - [ ]  Web3.js가 필요한 부분
            - [x]  회원가입 API
                - [x]  서버 계정 생성
            - [ ]  글 작성 시 보상토큰을 지급받는 API
            - [ ]  유저간 토큰을 전송하는 API
            - [ ]  특정 유저 정보를 가져오는 API
            - [ ]  ETH Faucet을 지급 받는 API
            - [ ]  NFT 구매를 위한 API
                - [ ]  유저 NFT 민팅
        - [ ]  Web3.js가 필요하지 않은 부분
            - [ ]  로그인 API
            - [ ]  게시판 GET API
            - [ ]  게시글 조회 GET API
    - 5) **Daemon 사용하여 트랜잭션 트래킹**
        - [ ]  Daemon 설치
        - [ ]  Daemon 실행 후 확인
- Recommended (권장) - 프로젝트를 통해 달성하기를 권장하는 항목입니다.
    - [ ]  HTTPS 설정
    - [ ]  DB ORM 라이브러리 이용하여 CRUD
    - [ ]  회원가입 / 로그인 과정을 토큰을 이용하여 구현
    - [ ]  Mint Multi Token 구현
